# Generated by Django 6.0.3 on 2026-03-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_theme_achievement_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='certificate_image',
        ),
        migrations.AddField(
            model_name='achievement',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
